name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: nuget restore
      run: nuget restore -Verbosity quiet

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      id: build
      run: |
        msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
        
    - name: create artifact 'TrxerConsole'
      uses: actions/checkout@v2
      with:
        name: TrxerConsole
        path: ${{ github.workspace }}\TrxerConsole\bin\Release\TrxerConsole.exe
